const PDFDocument = require('pdfkit');

/**
 * Generate a feedback PDF for a student's quiz result
 * @returns {Promise<Buffer>} PDF buffer
 */
const generateFeedbackPDF = async (data) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: 'A4',
        margins: { top: 60, bottom: 60, left: 50, right: 50 },
        info: {
          Title: 'Quiz Feedback Report',
          Author: 'AI Powered Quiz Application',
        },
      });

      const buffers = [];
      doc.on('data', (chunk) => buffers.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(buffers)));

      const { studentName, quizTitle, score, totalQuestions, percentage, feedback, submittedAt } = data;

      // === HEADER ===
      doc.rect(0, 0, doc.page.width, 120).fill('#1a1a2e');
      doc.fontSize(28).fillColor('#ffffff').text('AI Quiz Feedback Report', 50, 35, { align: 'center' });
      doc.fontSize(12).fillColor('#a0aec0').text('Generated by AI Powered Quiz Application', 50, 72, { align: 'center' });

      doc.moveDown(3);

      // === STUDENT INFO ===
      const infoY = 140;
      doc.roundedRect(40, infoY, doc.page.width - 80, 90, 8).fill('#f7fafc');
      doc.fontSize(11).fillColor('#4a5568');
      doc.text(`Student: ${studentName}`, 60, infoY + 15);
      doc.text(`Quiz: ${quizTitle}`, 60, infoY + 35);
      doc.text(`Date: ${new Date(submittedAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, 60, infoY + 55);

      // Score badge
      const scoreColor = percentage >= 80 ? '#48bb78' : percentage >= 60 ? '#ecc94b' : '#fc8181';
      doc.roundedRect(doc.page.width - 180, infoY + 10, 120, 65, 8).fill(scoreColor);
      doc.fontSize(24).fillColor('#ffffff').text(`${score}/${totalQuestions}`, doc.page.width - 175, infoY + 18, { width: 110, align: 'center' });
      doc.fontSize(14).text(`${percentage}%`, doc.page.width - 175, infoY + 48, { width: 110, align: 'center' });

      let currentY = infoY + 110;

      // === SECTION HELPER ===
      const drawSection = (title, items, color, icon) => {
        if (currentY > 680) {
          doc.addPage();
          currentY = 60;
        }
        doc.roundedRect(40, currentY, doc.page.width - 80, 4, 2).fill(color);
        currentY += 12;
        doc.fontSize(16).fillColor(color).text(`${icon}  ${title}`, 50, currentY);
        currentY += 28;

        if (items && items.length > 0) {
          items.forEach((item) => {
            if (currentY > 720) {
              doc.addPage();
              currentY = 60;
            }
            doc.fontSize(10).fillColor('#4a5568');
            doc.text(`•  ${item}`, 65, currentY, { width: doc.page.width - 130, lineGap: 3 });
            currentY += doc.heightOfString(`•  ${item}`, { width: doc.page.width - 130 }) + 8;
          });
        } else {
          doc.fontSize(10).fillColor('#a0aec0').text('No data available', 65, currentY);
          currentY += 20;
        }
        currentY += 15;
      };

      // === SECTIONS ===
      if (feedback) {
        drawSection('Strengths', feedback.strengths, '#48bb78', '★');
        drawSection('Areas for Improvement', feedback.weaknesses, '#fc8181', '△');
        drawSection('Suggestions', feedback.suggestions, '#667eea', '→');

        // Overall comment
        if (feedback.overallComment) {
          if (currentY > 650) {
            doc.addPage();
            currentY = 60;
          }
          doc.roundedRect(40, currentY, doc.page.width - 80, 4, 2).fill('#805ad5');
          currentY += 12;
          doc.fontSize(16).fillColor('#805ad5').text('Overall Assessment', 50, currentY);
          currentY += 28;
          doc.roundedRect(50, currentY, doc.page.width - 100, doc.heightOfString(feedback.overallComment, { width: doc.page.width - 140 }) + 20, 6).fill('#f0ebf8');
          doc.fontSize(11).fillColor('#553c9a').text(feedback.overallComment, 60, currentY + 10, { width: doc.page.width - 140, lineGap: 4 });
          currentY += doc.heightOfString(feedback.overallComment, { width: doc.page.width - 140 }) + 40;
        }
      }

      // === FOOTER ===
      const footerY = doc.page.height - 40;
      doc.fontSize(8).fillColor('#a0aec0')
        .text('This report was generated by AI and is for educational purposes only.', 50, footerY, { align: 'center' });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

module.exports = { generateFeedbackPDF };
